In [7]:
    from utils import utils
    dados = utils.get_base_de_dados()
    dados

       NUC   VAC   POX   ERL   MIT   ALM   GVH   MCG SEQUENCE NAME
0     0.58  0.61  0.47  0.13  0.50  0.00  0.48  0.22           MIT
1     0.43  0.67  0.48  0.27  0.50  0.00  0.53  0.22           MIT
2     0.64  0.62  0.49  0.15  0.50  0.00  0.53  0.22           MIT
3     0.58  0.44  0.57  0.13  0.50  0.00  0.54  0.22           NUC
4     0.42  0.44  0.48  0.54  0.50  0.00  0.48  0.22           MIT
...    ...   ...   ...   ...   ...   ...   ...   ...           ...
1479  0.81  0.62  0.43  0.17  0.50  0.00  0.53  0.22           ME2
1480  0.47  0.43  0.61  0.40  0.50  0.00  0.48  0.47           NUC
1481  0.67  0.57  0.36  0.19  0.50  0.00  0.56  0.22           ME2
1482  0.43  0.40  0.60  0.16  0.50  0.00  0.53  0.39           NUC
1483  0.65  0.54  0.54  0.13  0.50  0.00  0.53  0.22           CYT

[1484 rows x 9 columns]

In [12]:
nuc = dados['NUC']
vac = dados['VAC']
pox = dados['POX']
erl = dados['ERL']
mit = dados['MIT']
alm = dados['ALM']
gvh = dados['GVH']
mcg = dados['MCG']

dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1484 entries, 0 to 1483
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   NUC            1484 non-null   object
 1   VAC            1484 non-null   object
 2   POX            1484 non-null   object
 3   ERL            1484 non-null   object
 4   MIT            1484 non-null   object
 5   ALM            1484 non-null   object
 6   GVH            1484 non-null   object
 7   MCG            1484 non-null   object
 8   SEQUENCE NAME  1484 non-null   object
dtypes: object(9)
memory usage: 104.5+ KB

In [9]:
from scipy.stats import friedmanchisquare

fs = friedmanchisquare(nuc, vac, pox, erl, mit, alm, gvh, mcg)
fs

FriedmanchisquareResult(statistic=6485.641180080098, pvalue=0.0)

In [10]:
from scipy import stats
import scikit_posthocs as sp
import numpy as np

stats.friedmanchisquare(nuc, vac, pox, erl, mit, alm, gvh, mcg)

data = np.array([nuc, vac, pox, erl, mit, alm, gvh, mcg])

sp.posthoc_nemenyi_friedman(data.T)

DataError: No numeric types to aggregate